<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.User.Services\Ettad.User.Services.csproj" />
    <ProjectReference Include="..\Project.Comman\Ettad.CrossCutting.Comman.csproj" />
    <ProjectReference Include="..\Project.ResponseHandler\Ettad.CrossCutting.ResponseHandler.csproj" />
  </ItemGroup>

</Project>

