// <auto-generated />
using System;
using Ettad.EntityFramework.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ettad.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103065118_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ettad.Comman.Idenitity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ExtraEmployeesView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLdapUser")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ettad.CrossCutting.Comman.Idenitity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDefaultRole")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Ettad.Data.Entities.AllowanceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ItemId", "DepartmentId", "Year")
                        .IsUnique();

                    b.ToTable("AllowanceItems", (string)null);
                });

            modelBuilder.Entity("Ettad.Data.Entities.BaseItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("HccId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ReadyForIssue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HccId");

                    b.HasIndex("ItemNo")
                        .IsUnique();

                    b.ToTable("BaseItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Ettad.Data.Entities.CaseType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("CaseTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(2457),
                            IsDeleted = false,
                            NameAr = "نحاسي",
                            NameEn = "Brass"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(2576),
                            IsDeleted = false,
                            NameAr = "فولاذي",
                            NameEn = "Steel"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(2578),
                            IsDeleted = false,
                            NameAr = "ألومنيوم",
                            NameEn = "Aluminum"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(2580),
                            IsDeleted = false,
                            NameAr = "بلاستيك",
                            NameEn = "Plastic"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(2605),
                            IsDeleted = false,
                            NameAr = "مختلط",
                            NameEn = "Composite"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Color", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Colors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            NameAr = "أخضر",
                            NameEn = "Green"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            NameAr = "أسود",
                            NameEn = "Black"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            NameAr = "أصفر",
                            NameEn = "Yellow"
                        },
                        new
                        {
                            Id = 4L,
                            IsDeleted = false,
                            NameAr = "أحمر",
                            NameEn = "Red"
                        },
                        new
                        {
                            Id = 5L,
                            IsDeleted = false,
                            NameAr = "رمادي",
                            NameEn = "Gray"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Compatibility", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Compatibilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(6022),
                            IsDeleted = false,
                            NameAr = "المجموعة أ",
                            NameEn = "Group A"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(6041),
                            IsDeleted = false,
                            NameAr = "المجموعة ب",
                            NameEn = "Group B"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(6075),
                            IsDeleted = false,
                            NameAr = "المجموعة ج",
                            NameEn = "Group C"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(6077),
                            IsDeleted = false,
                            NameAr = "المجموعة د",
                            NameEn = "Group D"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(6079),
                            IsDeleted = false,
                            NameAr = "المجموعة هـ",
                            NameEn = "Group E"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "SA",
                            IsDeleted = false,
                            NameAr = "المملكة العربية السعودية",
                            NameEn = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "US",
                            IsDeleted = false,
                            NameAr = "الولايات المتحدة الأمريكية",
                            NameEn = "United States"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "UK",
                            IsDeleted = false,
                            NameAr = "المملكة المتحدة",
                            NameEn = "United Kingdom"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "FR",
                            IsDeleted = false,
                            NameAr = "فرنسا",
                            NameEn = "France"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "DE",
                            IsDeleted = false,
                            NameAr = "ألمانيا",
                            NameEn = "Germany"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "LOG",
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(9290),
                            IsDeleted = false,
                            NameAr = "قسم اللوجستيات",
                            NameEn = "Logistics Department"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "OPS",
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(9311),
                            IsDeleted = false,
                            NameAr = "قسم العمليات",
                            NameEn = "Operations Department"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "INV",
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(9313),
                            IsDeleted = false,
                            NameAr = "قسم المخزون",
                            NameEn = "Inventory Department"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "ARM",
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(9315),
                            IsDeleted = false,
                            NameAr = "قسم التسليح",
                            NameEn = "Armament Department"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "MNT",
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 132, DateTimeKind.Unspecified).AddTicks(9317),
                            IsDeleted = false,
                            NameAr = "قسم الصيانة",
                            NameEn = "Maintenance Department"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Depot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Depots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(858),
                            IsDeleted = false,
                            Latitude = 24.7136m,
                            Location = "Riyadh",
                            Longitude = 46.6753m,
                            NameAr = "مستودع الرياض المركزي",
                            NameEn = "Riyadh Central Depot"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(876),
                            IsDeleted = false,
                            Latitude = 21.5433m,
                            Location = "Jeddah",
                            Longitude = 39.1728m,
                            NameAr = "مستودع جدة الغربي",
                            NameEn = "Jeddah West Depot"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(878),
                            IsDeleted = false,
                            Latitude = 26.4207m,
                            Location = "Dammam",
                            Longitude = 50.0888m,
                            NameAr = "مستودع الدمام الشرقي",
                            NameEn = "Dammam East Depot"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(881),
                            IsDeleted = false,
                            Latitude = 21.2703m,
                            Location = "Taif",
                            Longitude = 40.4150m,
                            NameAr = "مستودع الطائف الجنوبي",
                            NameEn = "Taif South Depot"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.HazardDivision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("HazardDivisions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(2333),
                            IsDeleted = false,
                            NameAr = "القسم 1.1 - مواد متفجرة",
                            NameEn = "Division 1.1 - Explosives"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(2344),
                            IsDeleted = false,
                            NameAr = "القسم 1.2 - مواد قابلة للانفجار",
                            NameEn = "Division 1.2 - Projection Hazard"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(2346),
                            IsDeleted = false,
                            NameAr = "القسم 1.3 - مواد قابلة للاشتعال",
                            NameEn = "Division 1.3 - Fire Hazard"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(2348),
                            IsDeleted = false,
                            NameAr = "القسم 1.4 - مواد منخفضة المخاطر",
                            NameEn = "Division 1.4 - Minor Hazard"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(2350),
                            IsDeleted = false,
                            NameAr = "القسم 1.5 - مواد غير حساسة",
                            NameEn = "Division 1.5 - Very Insensitive"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Hcc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Hcc", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(3797),
                            IsDeleted = false,
                            NameAr = "HCC-A1",
                            NameEn = "HCC-A1"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(3808),
                            IsDeleted = false,
                            NameAr = "HCC-B2",
                            NameEn = "HCC-B2"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(3810),
                            IsDeleted = false,
                            NameAr = "HCC-C3",
                            NameEn = "HCC-C3"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(3812),
                            IsDeleted = false,
                            NameAr = "HCC-D4",
                            NameEn = "HCC-D4"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 133, DateTimeKind.Unspecified).AddTicks(3813),
                            IsDeleted = false,
                            NameAr = "HCC-E5",
                            NameEn = "HCC-E5"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DepoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecievedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("Ettad.Data.Entities.InventoryDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentQuantity")
                        .HasColumnType("bigint");

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemQuantity")
                        .HasColumnType("bigint");

                    b.Property<int>("Lot")
                        .HasColumnType("int");

                    b.Property<long?>("ManufacturerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SupplierId");

                    b.ToTable("InventoryDetails", (string)null);
                });

            modelBuilder.Entity("Ettad.Data.Entities.Manufacturer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Manufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(715),
                            IsDeleted = false,
                            NameAr = "مصنع الذخائر الملكي",
                            NameEn = "Royal Ordnance Factory"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(760),
                            IsDeleted = false,
                            NameAr = "شركة رايثيون",
                            NameEn = "Raytheon Company"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(765),
                            IsDeleted = false,
                            NameAr = "مؤسسة الصناعات العسكرية الوطنية",
                            NameEn = "National Military Industries"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(767),
                            IsDeleted = false,
                            NameAr = "شركة لوكهيد مارتن",
                            NameEn = "Lockheed Martin"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(769),
                            IsDeleted = false,
                            NameAr = "مجموعة بي إيه إي سيستمز",
                            NameEn = "BAE Systems"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.NatureOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("NatureOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(2283),
                            IsDeleted = false,
                            NameAr = "قتالية",
                            NameEn = "Combat"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(2294),
                            IsDeleted = false,
                            NameAr = "تدريبية",
                            NameEn = "Training"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(2296),
                            IsDeleted = false,
                            NameAr = "تعليمية",
                            NameEn = "Educational"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(2298),
                            IsDeleted = false,
                            NameAr = "وهمية",
                            NameEn = "Dummy"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(2299),
                            IsDeleted = false,
                            NameAr = "عرض",
                            NameEn = "Display"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Nsn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Nsn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(3676),
                            IsDeleted = false,
                            NameAr = "NSN-1005-01-123-4567",
                            NameEn = "NSN-1005-01-123-4567"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(3685),
                            IsDeleted = false,
                            NameAr = "NSN-1010-01-234-5678",
                            NameEn = "NSN-1010-01-234-5678"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(3687),
                            IsDeleted = false,
                            NameAr = "NSN-1015-01-345-6789",
                            NameEn = "NSN-1015-01-345-6789"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(3689),
                            IsDeleted = false,
                            NameAr = "NSN-1020-01-456-7890",
                            NameEn = "NSN-1020-01-456-7890"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(3690),
                            IsDeleted = false,
                            NameAr = "NSN-1025-01-567-8901",
                            NameEn = "NSN-1025-01-567-8901"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.PrimaryPurpos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PrimaryPurposes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(5029),
                            IsDeleted = false,
                            NameAr = "قتالي",
                            NameEn = "Combat"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(5040),
                            IsDeleted = false,
                            NameAr = "تدريبي",
                            NameEn = "Training"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(5042),
                            IsDeleted = false,
                            NameAr = "دفاعي",
                            NameEn = "Defense"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(5044),
                            IsDeleted = false,
                            NameAr = "استطلاعي",
                            NameEn = "Reconnaissance"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(5046),
                            IsDeleted = false,
                            NameAr = "هجومي",
                            NameEn = "Offensive"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.ProjectailMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ProjectailMaterials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(6426),
                            IsDeleted = false,
                            NameAr = "فولاذ",
                            NameEn = "Steel"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(6437),
                            IsDeleted = false,
                            NameAr = "نحاس",
                            NameEn = "Brass"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(6439),
                            IsDeleted = false,
                            NameAr = "رصاص",
                            NameEn = "Lead"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(6440),
                            IsDeleted = false,
                            NameAr = "تنغستن",
                            NameEn = "Tungsten"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(6442),
                            IsDeleted = false,
                            NameAr = "يورانيوم منضب",
                            NameEn = "Depleted Uranium"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Propellant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Propellants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(7775),
                            IsDeleted = false,
                            NameAr = "بارود أحادي القاعدة",
                            NameEn = "Single-base Powder"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(7786),
                            IsDeleted = false,
                            NameAr = "بارود ثنائي القاعدة",
                            NameEn = "Double-base Powder"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(7788),
                            IsDeleted = false,
                            NameAr = "بارود ثلاثي القاعدة",
                            NameEn = "Triple-base Powder"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(7789),
                            IsDeleted = false,
                            NameAr = "نيتروسليلوز",
                            NameEn = "Nitrocellulose"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(7791),
                            IsDeleted = false,
                            NameAr = "كورديت",
                            NameEn = "Cordite"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Settings.EmailConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailConfigurations");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(9106),
                            IsDeleted = false,
                            NameAr = "شركة الإمدادات العسكرية المتقدمة",
                            NameEn = "Advanced Military Supplies Co."
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(9116),
                            IsDeleted = false,
                            NameAr = "المؤسسة العامة للتسليح",
                            NameEn = "General Armament Corporation"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(9118),
                            IsDeleted = false,
                            NameAr = "شركة الصناعات الدفاعية",
                            NameEn = "Defense Industries Company"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(9120),
                            IsDeleted = false,
                            NameAr = "مجموعة التجهيزات العسكرية",
                            NameEn = "Military Equipment Group"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 134, DateTimeKind.Unspecified).AddTicks(9121),
                            IsDeleted = false,
                            NameAr = "شركة التوريدات الاستراتيجية",
                            NameEn = "Strategic Supplies Corporation"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 135, DateTimeKind.Unspecified).AddTicks(383),
                            IsDeleted = false,
                            NameAr = "قطعة",
                            NameEn = "Piece"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 135, DateTimeKind.Unspecified).AddTicks(393),
                            IsDeleted = false,
                            NameAr = "صندوق",
                            NameEn = "Box"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 135, DateTimeKind.Unspecified).AddTicks(395),
                            IsDeleted = false,
                            NameAr = "طن",
                            NameEn = "Ton"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 135, DateTimeKind.Unspecified).AddTicks(396),
                            IsDeleted = false,
                            NameAr = "كيلوغرام",
                            NameEn = "Kilogram"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2025, 11, 3, 9, 51, 18, 135, DateTimeKind.Unspecified).AddTicks(398),
                            IsDeleted = false,
                            NameAr = "حاوية",
                            NameEn = "Container"
                        });
                });

            modelBuilder.Entity("Ettad.Data.Entities.Workflows.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartementId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("RequesterType")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Workflows.WorkflowApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDelagation")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetRequestId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("WorkflowApprovalHistory");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ApproverType")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustApprove")
                        .HasColumnType("bit");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ettad.Data.Entities.Ammunition", b =>
                {
                    b.HasBaseType("Ettad.Data.Entities.BaseItem");

                    b.Property<decimal>("BulletDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BulletDiameterUnitId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CaseLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CaseLengthUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("CaseTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompatibilityId")
                        .HasColumnType("bigint");

                    b.Property<long>("HazardDivisionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLinked")
                        .HasColumnType("bit");

                    b.Property<long?>("NatureOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("NsnId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PrimaryPurposId")
                        .HasColumnType("bigint");

                    b.Property<string>("Primer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectailMaterialId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectileColorId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropellantId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("BulletDiameterUnitId");

                    b.HasIndex("CaseLengthUnitId");

                    b.HasIndex("CaseTypeId");

                    b.HasIndex("CompatibilityId");

                    b.HasIndex("HazardDivisionId");

                    b.HasIndex("NatureOptionId");

                    b.HasIndex("NsnId");

                    b.HasIndex("PrimaryPurposId");

                    b.HasIndex("ProjectailMaterialId");

                    b.HasIndex("ProjectileColorId");

                    b.HasIndex("PropellantId");

                    b.ToTable("Ammunitions", (string)null);
                });

            modelBuilder.Entity("Ettad.Data.Entities.AllowanceItem", b =>
                {
                    b.HasOne("Ettad.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ettad.Data.Entities.BaseItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Ettad.Data.Entities.BaseItem", b =>
                {
                    b.HasOne("Ettad.Data.Entities.Hcc", "Hcc")
                        .WithMany()
                        .HasForeignKey("HccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hcc");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Inventory", b =>
                {
                    b.HasOne("Ettad.Data.Entities.Depot", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depo");
                });

            modelBuilder.Entity("Ettad.Data.Entities.InventoryDetail", b =>
                {
                    b.HasOne("Ettad.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.Inventory", "Inventory")
                        .WithMany("InventoryDetails")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ettad.Data.Entities.BaseItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ettad.Data.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("Inventory");

                    b.Navigation("Item");

                    b.Navigation("Manufacturer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Workflows.WorkflowApprovalHistory", b =>
                {
                    b.HasOne("Ettad.Data.Entities.Workflows.WorkflowStep", "WorkflowStep")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.HasOne("Ettad.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Ettad.CrossCutting.Comman.Idenitity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ettad.Comman.Idenitity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ettad.Comman.Idenitity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Ettad.CrossCutting.Comman.Idenitity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ettad.Comman.Idenitity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ettad.Comman.Idenitity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ettad.Data.Entities.Ammunition", b =>
                {
                    b.HasOne("Ettad.Data.Entities.Unit", "BulletDiameterUnit")
                        .WithMany()
                        .HasForeignKey("BulletDiameterUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ettad.Data.Entities.Unit", "CaseLengthUnit")
                        .WithMany()
                        .HasForeignKey("CaseLengthUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ettad.Data.Entities.CaseType", "CaseType")
                        .WithMany()
                        .HasForeignKey("CaseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.Compatibility", "Compatibility")
                        .WithMany()
                        .HasForeignKey("CompatibilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.HazardDivision", "HazardDivision")
                        .WithMany()
                        .HasForeignKey("HazardDivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.BaseItem", null)
                        .WithOne()
                        .HasForeignKey("Ettad.Data.Entities.Ammunition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ettad.Data.Entities.NatureOption", "NatureOption")
                        .WithMany()
                        .HasForeignKey("NatureOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.Nsn", "Nsn")
                        .WithMany()
                        .HasForeignKey("NsnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ettad.Data.Entities.PrimaryPurpos", "PrimaryPurpos")
                        .WithMany()
                        .HasForeignKey("PrimaryPurposId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.ProjectailMaterial", "ProjectailMaterial")
                        .WithMany()
                        .HasForeignKey("ProjectailMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.Color", "ProjectileColor")
                        .WithMany()
                        .HasForeignKey("ProjectileColorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ettad.Data.Entities.Propellant", "Propellant")
                        .WithMany()
                        .HasForeignKey("PropellantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BulletDiameterUnit");

                    b.Navigation("CaseLengthUnit");

                    b.Navigation("CaseType");

                    b.Navigation("Compatibility");

                    b.Navigation("HazardDivision");

                    b.Navigation("NatureOption");

                    b.Navigation("Nsn");

                    b.Navigation("PrimaryPurpos");

                    b.Navigation("ProjectailMaterial");

                    b.Navigation("ProjectileColor");

                    b.Navigation("Propellant");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryDetails");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Workflows.Workflow", b =>
                {
                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("Ettad.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.Navigation("ApprovalHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
