using AutoMapper;
using Ettad.Data.Entities;
using Ettad.Data.Enums;
using Ettad.RequestManagement.Service.Returns.Dtos;
using Ettad.RequestManagement.Service.Common.Dtos;

namespace Ettad.RequestManagement.Service.Returns.Profiles
{
    public class ReturnMappingProfile : Profile
    {
        public ReturnMappingProfile()
        {
            // Entity to DTO - Use base mapping which handles RequestItems automatically
            CreateMap<Return, ReturnDto>()
                .IncludeBase<BaseRequest, BaseRequestDto>();

            // Create DTO to Entity
            CreateMap<CreateReturnDto, Return>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.RequestNo, opt => opt.Ignore()) // Generated by RequestNoGeneratorService
                .ForMember(dest => dest.CreationDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.ModificationDate, opt => opt.Ignore())
                .ForMember(dest => dest.ModifiedBy, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.DeletionDate, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedBy, opt => opt.Ignore())
                .ForMember(dest => dest.Department, opt => opt.Ignore())
                .ForMember(dest => dest.Requester, opt => opt.Ignore())
                .ForMember(dest => dest.Reciever, opt => opt.Ignore())
                .ForMember(dest => dest.Depot, opt => opt.Ignore())
                .ForMember(dest => dest.RequestPurpose, opt => opt.Ignore())
                .ForMember(dest => dest.RequestItems, opt => opt.Ignore()) // Handle separately
                .ForMember(dest => dest.RequestType, opt => opt.MapFrom(src => RequestType.Return)) // Always set to Return by backend
                .ForMember(dest => dest.Priority, opt => opt.MapFrom(src => Enum.Parse<RequestPriority>(src.Priority, true))) // Validator ensures valid value
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => RequestStatus.New)); // Always set to New by backend

            CreateMap<CreateReturnItemDto, RequestItem>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.RequestId, opt => opt.Ignore())
                .ForMember(dest => dest.Item, opt => opt.Ignore())
                .ForMember(dest => dest.Request, opt => opt.Ignore());
        }
    }
}

